allowBuilds:
  "@google/genai": true
  koffi: true
  node-llama-cpp: true
  openclaw: true
  protobufjs: true
  sharp: true
  tree-sitter-bash: true
  tree-sitter-go: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
minimumReleaseAgeExclude:
  - '@wei840222/qmd@2026.9.6'
  - '@openclaw/ai@2026.9.3 || 2026.9.5'
  - openclaw@2026.9.3 || 2026.9.5

overrides:
  "@node-llama-cpp/linux-arm64": "-"
  "@node-llama-cpp/linux-armv7l": "-"
  "@node-llama-cpp/linux-riscv64": "-"
  "@node-llama-cpp/linux-x64-cuda": "-"
  "@node-llama-cpp/linux-x64-cuda-ext": "-"
  "@node-llama-cpp/linux-x64-vulkan": "-"
  "@node-llama-cpp/mac-arm64-metal": "-"
  "@node-llama-cpp/mac-x64": "-"
  "@node-llama-cpp/win-arm64": "-"
  "@node-llama-cpp/win-x64": "-"
  "@node-llama-cpp/win-x64-cuda": "-"
  "@node-llama-cpp/win-x64-cuda-ext": "-"
  "@node-llama-cpp/win-x64-vulkan": "-"
